language: python
python:
  - "3.6"
before_install:
  - pip install pytest
  - pip install pytest-cov
  - pip install pylint
install:
  - pip install -r requirements.txt
script:
  - pylint cloudnetpy/categorize/*.py
  - pytest --cov=cloudnetpy tests/unit/
