name: "Generate documentation"

on:
  push:
    # tags:
    #   - '*'

jobs:
  docs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install .
          pip install -r docs/requirements.txt
      - name: Build documentation
        run: |
          cd docs
          make html
          touch html/.nojekyll
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b gh-pages
          git add -f docs/html
          git commit -m "Generate documentation"
          git filter-branch --prune-empty --subdirectory-filter docs/html gh-pages
          git push origin gh-pages -f
